apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: nodejs-pipeline-run
spec:
  serviceAccountName: pipeline-run-sa
  pipelineRef:
    name: nodejs-pipeline
  params:
    - name: DEPLOY_ENVIRONMENT
      value: "env-dev"
    - name: IMAGE_NAME
      value: "nodejs-app"
    - name: git-repo
      value: "https://github.com/khushilms-cs19/nodejs-tekton-prac.git"
    - name: git-revision
      value: "main"
