apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy-nodejs-app
spec:
  params:
    - name: DEPLOY_ENVIRONMENT
      description: The environment where you deploy the app
      default: "env-dev"
      type: string
    - name: IMAGE_NAME
      description: The name of the image
      default: "nodejs-app"
      type: string
    - name: git-repo
      description: The git repo where the source code is stored
      default: "https://github.com/khushilms-cs19/nodejs-tekton-prac.git"
      type: string
    - name: git-revision
      description: The git revision
      default: "main"
      type: string
    - name: deploy-file
      description: The file to deploy
      default: "https://github.com/khushilms-cs19/nodejs-tekton-prac/tree/main/tekton/task-deploy.yaml"
      type: string
  steps:
    - name: deploy-resources
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "$(params.deploy-file)"
        - "-n"
        - "$(params.DEPLOY_ENVIRONMENT)"
    - name: deploy-application
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "rollout"
        - "restart"
        - "deployment/nodejs-app"
        - "-n"
        - "$(params.DEPLOY_ENVIRONMENT)"
