apiVersion: v1
kind: Secret
metadata:
  name: docker-creds
  annotations:
    tekton.dev/docker-0: https://index.docker.io
type: kubernetes.io/basic-auth
stringData:
  username: "khushilms"
  password: "Khushil@2001"
