apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: nodejs-pipeline
spec:
  params:
    - name: IMAGE
      description: Image description
      type: string
      default: "khushilms/nodejs-demo"
    - name: TAG
      description: Preferred tag
      default: latest
  workspaces:
    - name: node-workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: node-workspace
      params:
        - name: url
          value: "https://github.com/khushilms-cs19/nodejs-tekton-prac.git"
        - name: revision
          value: "main"
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
    - name: build-push-image
      taskRef:
        name: push-image
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: node-workspace
      params:
        - name: IMAGE
          value: "$(params.IMAGE):$(params.TAG)"
        - name: CONTEXT
          value: "source"
        - name: FORMAT
          value: "docker"
