apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: nodejs-app-event-listener
spec:
  serviceAccountName: tekton-robot
  triggers:
    - name: nodejs-app-trigger
      bindings:
        - ref: nodejs-app-trigger-binding
      template:
        ref: nodejs-app-trigger-template
