apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: nodejs-pipeline
spec:
  params:
    - name: git-repo
      description: The git repo where the source code is stored
      default: "https://github.com/khushilms-cs19/nodejs-tekton-prac.git"
      type: string
    - name: git-revision
      description: The git revision
      default: "main"
      type: string
    - name: image-reference
      type: string
  # workspaces:
  #   - name: docker-creds
  #     # secret:
  #     #   secretName: docker-creds
  #   - name: shared-data
  tasks:
    # - name: build
    #   taskRef:
    #     name: build-nodejs-app
    #   params:
    #     - name: git-repo
    #       value: "$(params.git-repo)"
    #     - name: git-revision
    #       value: "$(params.git-revision)"
    - name: fetch-source
      taskRef:
        name: build-nodejs-app
      # workspaces:
      #   - name: output
      #     workspace: shared-data
      # params:
      #   - name: url
      #     value: "$(params.git-repo)"
      #   - name: revision
      #     value: "$(params.git-revision)"
      params:
        - name: git-repo
          value: "$(params.git-repo)"
        - name: git-revision
          value: "$(params.git-revision)"

    # - name: build-push
    #   runAfter:
    #     - fetch-source
    #   taskRef:
    #     name: kaniko
    #   workspaces:
    #     - name: source
    #       workspace: shared-data
    #   params:
    #     - name: IMAGE
    #       value: "$(params.image-reference)"
    # - name: create-deployment
    #   runAfter:
    #     - build-push
    #   taskRef:
    #     name: deploy-nodejs-app
    #   params:
    #     - name: IMAGE
    #       value: "$(params.image-reference)"
