apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: nodejs-pipeline
spec:
  params:
    - name: git-repo
      description: The git repo where the source code is stored
      default: "https://github.com/khushilms-cs19/nodejs-tekton-prac.git"
      type: string
    - name: git-revision
      description: The git revision
      default: "main"
      type: string
  tasks:
    - name: build
      taskRef:
        name: build-nodejs-app
      params:
        - name: git-repo
          value: "$(params.git-repo)"
        - name: git-revision
          value: "$(params.git-revision)"
