apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-nodejs-app
spec:
  params:
    - name: IMAGE_NAME
      description: The name of the image
      default: "nodejs-app"
      type: string
    - name: git-repo
      description: The git repo where the source code is stored
      default: "https://github.com/khushilms-cs19/nodejs-tekton-prac.git"
      type: string
    - name: git-revision
      description: The git revision
      default: "main"
      type: string
    - name: git-payload
      description: The git payload
      default: "test"
      type: string
  steps:
    - name: build-nodejs
      image: alpine
      workingDir: /workspace/source
      command:
        - sh
      args:
        - -c
        - |
          apk add --no-cache git nodejs npm
          echo "git-payload: $(params.git-payload)"
          git clone $(params.git-repo) .
          git checkout $(params.git-revision)

          npm install
          node index.js
