apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: nodejs-app-trigger-template
spec:
  params:
    - name: git-repo
      description: The git repo where the source code is stored
      default: "https://github.com/khushilms-cs19/nodejs-tekton-prac.git"
    - name: git-revision
      description: The git revision
      default: "main"
    - name: image-reference
    - name: git-payload

  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: nodejs-pipeline-run-
      spec:
        pipelineRef:
          name: nodejs-pipeline
        workspaces:
          - name: docker-creds
            secret:
              secretName: docker-creds
        params:
          - name: git-repo
            value: "$(tt.params.git-repo)"
          - name: git-revision
            value: "$(tt.params.git-revision)"
          - name: image-reference
            value: "$(tt.params.image-reference)"
          - name: git-payload
            value: "$(tt.params.git-payload)"
