apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: nodejs-app-trigger-binding
spec:
  params:
    - name: git-repo
      value: $(body.head_commit.url)
    - name: git-revision
      value: $(body.head_commit.id)
    - name: image-reference
      value: docker.io/khushilms/nodejs-demo
